# Generated by Django 5.2.17 on 2026-09-05 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='Libellé')),
                ('type', models.CharField(choices=[('surcout', 'Surcoût'), ('retard', 'Retard')], max_length=20, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Cause',
                'verbose_name_plural': 'Causes',
                'ordering': ['type', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code fournisseur')),
                ('category', models.CharField(choices=[('transporteur', 'Transporteur'), ('transitaire', 'Transitaire'), ('agent_maritime', 'Agent maritime'), ('autre', 'Autre')], default='transporteur', max_length=30, verbose_name='Catégorie')),
                ('service_type', models.CharField(blank=True, max_length=100, verbose_name='Type de prestation')),
                ('contact', models.CharField(blank=True, max_length=150, verbose_name='Contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('declaration_ref', models.CharField(blank=True, max_length=50, verbose_name='Référence déclaration')),
                ('order_date', models.DateField(verbose_name='Date de commande')),
                ('service_type', models.CharField(choices=[('maritime', 'Maritime'), ('routier', 'Routier'), ('aerien', 'Aérien'), ('ferroviaire', 'Ferroviaire')], default='routier', max_length=20, verbose_name='Type de prestation')),
                ('origin', models.CharField(max_length=150, verbose_name='Origine')),
                ('destination', models.CharField(max_length=150, verbose_name='Destination')),
                ('planned_date', models.DateField(verbose_name='Date prévue')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Date réelle')),
                ('planned_cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Coût prévu (MAD)')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Coût réel (MAD)')),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('livree', 'Livrée'), ('retardee', 'Retardée'), ('annulee', 'Annulée')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('source', models.CharField(choices=[('reelle', 'Donnée réelle'), ('demo', 'Donnée de démonstration')], default='demo', max_length=10, verbose_name='Origine des données')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(max_length=150, verbose_name='Type de problème')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Coût du litige (MAD)')),
                ('impact', models.CharField(blank=True, max_length=150, verbose_name='Impact')),
                ('status', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours de traitement'), ('resolu', 'Résolu'), ('clos', 'Clos')], default='ouvert', max_length=20, verbose_name='Statut')),
                ('corrective_action', models.TextField(blank=True, verbose_name='Action corrective')),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.cause', verbose_name='Cause')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='dashboard.order', verbose_name='Commande')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='dashboard.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Litige',
                'verbose_name_plural': 'Litiges',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=255, verbose_name='Problème identifié')),
                ('action', models.TextField(verbose_name='Action proposée')),
                ('responsible', models.CharField(max_length=150, verbose_name='Responsable')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('deadline', models.DateField(verbose_name='Date limite')),
                ('priority', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], default='moyenne', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('realise', 'Réalisé'), ('annule', 'Annulé')], default='a_faire', max_length=20, verbose_name='Statut')),
                ('expected_result', models.TextField(blank=True, verbose_name='Résultat attendu')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.cause', verbose_name='Cause')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='dashboard.supplier', verbose_name='Fournisseur concerné')),
            ],
            options={
                'verbose_name': 'Action du plan',
                'verbose_name_plural': "Plan d'action",
                'ordering': ['-priority', 'deadline'],
            },
        ),
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence transit')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('planned_clearance_date', models.DateField(blank=True, null=True, verbose_name='Date prévue de dédouanement')),
                ('actual_clearance_date', models.DateField(blank=True, null=True, verbose_name='Date réelle de dédouanement')),
                ('planned_duration', models.IntegerField(blank=True, null=True, verbose_name='Durée prévue (jours)')),
                ('actual_duration', models.IntegerField(blank=True, null=True, verbose_name='Durée réelle (jours)')),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Frais de transit (MAD)')),
                ('additional_fees', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Frais supplémentaires (MAD)')),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('dedouane', 'Dédouané'), ('bloque', 'Bloqué'), ('retarde', 'Retardé')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('delay_cause', models.ForeignKey(blank=True, limit_choices_to={'type': 'retard'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.cause', verbose_name='Cause du retard')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transits', to='dashboard.order', verbose_name='Commande')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transits', to='dashboard.supplier', verbose_name='Fournisseur / Transitaire')),
            ],
            options={
                'verbose_name': 'Transit',
                'verbose_name_plural': 'Transits',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence transport')),
                ('mode', models.CharField(choices=[('maritime', 'Maritime'), ('routier', 'Routier'), ('aerien', 'Aérien'), ('ferroviaire', 'Ferroviaire')], max_length=20, verbose_name='Mode de transport')),
                ('origin', models.CharField(max_length=150, verbose_name='Origine')),
                ('destination', models.CharField(max_length=150, verbose_name='Destination')),
                ('planned_departure', models.DateField(blank=True, null=True, verbose_name='Date de départ prévue')),
                ('actual_departure', models.DateField(blank=True, null=True, verbose_name='Date de départ réelle')),
                ('planned_arrival', models.DateField(blank=True, null=True, verbose_name="Date d'arrivée prévue")),
                ('actual_arrival', models.DateField(blank=True, null=True, verbose_name="Date d'arrivée réelle")),
                ('planned_cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Coût prévu (MAD)')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Coût réel (MAD)')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distance (km)')),
                ('quantity', models.CharField(blank=True, max_length=100, verbose_name='Quantité / Contenants')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Poids (kg)')),
                ('status', models.CharField(choices=[('planifie', 'Planifié'), ('en_transit', 'En transit'), ('arrive', 'Arrivé'), ('retarde', 'Retardé')], default='planifie', max_length=20, verbose_name='Statut')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='dashboard.order', verbose_name='Commande')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='dashboard.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
                'ordering': ['-planned_departure'],
            },
        ),
    ]
